// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teams.Infrastructure;

#nullable disable

namespace Teams.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230116180050_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teams.Application.Commands.IdentifiedCommand.Request.IdentifiedCommandRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_requests");

                    b.ToTable("requests", "public");
                });

            modelBuilder.Entity("Teams.Domain.Models.CityAggregate.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("cities", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Atlanta"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Boston"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Charlotte"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chicago"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cleveland"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Detroit"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Los Angeles"
                        });
                });

            modelBuilder.Entity("Teams.Domain.Models.TeamAggregate.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("cityid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("SalaryBasket")
                        .HasColumnType("double precision")
                        .HasColumnName("salarybasket");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CityId" }, "nbateams_cityid_idx");

                    b.ToTable("nbateams", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Hawks",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            Name = "Celtics",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            Name = "Hornets",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 4,
                            CityId = 4,
                            Name = "Bulls",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 5,
                            CityId = 5,
                            Name = "Cavaliers",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 6,
                            CityId = 6,
                            Name = "Pistons",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 7,
                            CityId = 7,
                            Name = "Clippers",
                            SalaryBasket = 0.0
                        },
                        new
                        {
                            Id = 8,
                            CityId = 7,
                            Name = "Lakers",
                            SalaryBasket = 0.0
                        });
                });

            modelBuilder.Entity("Teams.Infrastructure.IntegrationEvents.EventLog.Models.IntegrationEventLog", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("eventType");

                    b.Property<int>("SendAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("sendAttempts");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transactionId");

                    b.HasKey("EventId")
                        .HasName("pk_eventlog");

                    b.ToTable("eventlog", "public");
                });

            modelBuilder.Entity("Teams.Domain.Models.TeamAggregate.Team", b =>
                {
                    b.HasOne("Teams.Domain.Models.CityAggregate.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("City");
                });
#pragma warning restore 612, 618
        }
    }
}
