DO
$$
BEGIN
    IF EXISTS (
	   SELECT FROM information_schema.tables 
	   WHERE  table_schema = 'public'
	   AND    table_name   = 'players'
	) 
	THEN DROP TABLE public.players;
	END IF;

    IF EXISTS (
	   SELECT FROM information_schema.tables 
	   WHERE  table_schema = 'public'
	   AND    table_name   = 'nbateams'
	) 
	THEN DROP TABLE public.nbateams;
	END IF;

    IF EXISTS (
	   SELECT FROM information_schema.tables 
	   WHERE  table_schema = 'public'
	   AND    table_name   = 'cities'
	) 
	THEN DROP TABLE public.cities;
	END IF;
END
$$;

-- public.cities definition
CREATE TABLE public.cities (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NULL,
	CONSTRAINT cities_pk PRIMARY KEY (id)
);

-- public.nbateams definition
CREATE TABLE public.nbateams (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"name" varchar NULL,
	cityid int4 NULL,
	CONSTRAINT nbateams_pk PRIMARY KEY (id),
    CONSTRAINT nbateams_fk FOREIGN KEY (cityid) REFERENCES public.cities(id) ON DELETE SET NULL
);

-- public.players definition
CREATE TABLE public.players (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	birthday date NULL,
	firstname varchar NULL,
	lastname varchar NULL,
	nbateamid int4 NULL,
	CONSTRAINT players_pk PRIMARY KEY (id),
    CONSTRAINT players_fk FOREIGN KEY (nbateamid) REFERENCES public.nbateams(id) ON DELETE SET NULL
);
