apiVersion: v1
kind: Service
metadata:
  name: playersnpservice-srv
spec:
  type: NodePort
  selector:
    app: playersservice
  ports:
    - name: playersservice
      protocol: TCP
      port: 80
      targetPort: 80
