apiVersion: v1
kind: Service
metadata:
  name: teamsnpservice-srv
spec:
  type: NodePort
  selector:
    app: teamsservice
  ports:
    - name: teamsservice
      protocol: TCP
      port: 80
      targetPort: 80
